language: bash

before_install: cd .. && mkdir server && cd server && wget -O - -q get.pocketmine.net | bash -s - -v development

install:
  - cd $TRAVIS_BUILD_DIR/../server && mkdir plugins && cd plugins
  - wget https://github.com/PocketMine/DevTools/releases/download/v1.10.0/DevTools_v1.10.0.phar
  - wget https://gist.githubusercontent.com/PEMapModder/46a4c61fcd855d14db9a/raw/932587edf6789e975ae1a32956cdc5bafac96ade/ServerStop.php

before_script: cp -R $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../server/plugins/EssentialsPE

script: ./start.sh --disable-ansi
