name: EssentialsPE
main: EssentialsPE\Loader
version: 1.0.0
api: [1.0.0]
author: LegendsofMCPE Team

permissions:
    essentials:
        default: op
        description: "All the Essentials' features"
        children:
            essentials.broadcast:
                default: op
                description: "Broadcast a message"
            essentials.burn:
                default: op
                description: "Set a player on fire"
            essentials.colorchat:
                default: op
                description: "Allow the player to talk with colored messages"
            essentials.essentials:
                default: op
                description: "See the current Essentials version"
            essentials.extinguish:
                default: op
                description: "Extinguish a player"
                children:
                  essentials.extinguish.use:
                    default: op
                    description: "Extinguish yourslef"
                  essentials.extinguish.other:
                    default: op
                    description: "Extinguish other players"
            essentials.getpos:
                default: op
                description: "Get any player's position"
                children:
                    essentials.getpos.use:
                        default: true
                        description: "Get your curren position"
                    essentials.getpos.other:
                        default: op
                        description: "Get other player's position"
            essentials.heal:
                default: op
                description: "Heal yourself or other players"
                children:
                    essentials.heal.use:
                        default: op
                        description: "Heal yourself"
                    essentials.heal.other:
                        default: op
                        description: "Heal other players"
            essentials.more:
                default: op
                description: "Get a stack of the item you're holding"
            essentials.nick:
                default: op
                description: "Change your or others name"
                children:
                    essentials.nick.use:
                        default: op
                        description: "Change your name"
                    essentials.nick.other:
                        default: op
                        desctiption: "Change others name"
            essentials.realname:
                default: op
                description: "See a player's realname"
            essentials.repair:
                default: op
                description: "Repair the item you're holding"
            essentials.seen:
                default: op
                description: "Check player's last online time"
            essentials.setspawn:
                default: op
                description: "Change your server's general spawn"
