# EssentialsPE configuration
# This configuration flie let you modify how EssentialsPE work with some features

# This option let you disable player damage when they're AFK
safe-afk: true
# Time until the server kick an AFK player (in seconds)
# Set it to -1 for not timeout
auto-afk-kick: 300

# Let you configure the size of a stack that players (with permission) can get (via /more or /item)
oversized-stacks: 64

# Let you set a limit for the /near command to search for players (in meters)
near-radius-limit: 200
# Let you set a default value to search for players (it can't be higher than the default limit)
near-default-radius: 200

# This option let you enable color codes in the server, but keep in mind that the client may not support them
enable-custom-colors: false

# These options will let you configure how the auto-updater will work
updater:
  # Enable it?
  enabled: true
  # Allow to set a time interval for the auto-updater to work (In seconds) [Default is 30 minutes {1800 seconds}]
  time-interval: 1800
  # Do you want to warn the console?
  warn-console: true
  # Do you want to warn players with the permission 'essentials.update'?
  warn-players: true
  # Do you want to use 'stable' releases? If not, beta ones will be used instead
  stable: true